"""initial_learning_schema_with_user_id

Revision ID: 1e04a0ab1067
Revises: 
Create Date: 2026-02-27 12:24:12.490389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
import memu.database.postgres.models  
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1e04a0ab1067'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', memu.database.postgres.models.TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', memu.database.postgres.models.TZDateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='learning'
    )
    op.create_index(op.f('ix_learning_memory_categories_id'), 'memory_categories', ['id'], unique=False, schema='learning')
    op.create_index(op.f('ix_learning_memory_categories_name'), 'memory_categories', ['name'], unique=False, schema='learning')
    op.create_index('ix_memory_categories__scope', 'memory_categories', ['user_id'], unique=False, schema='learning')
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', memu.database.postgres.models.TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', memu.database.postgres.models.TZDateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='learning'
    )
    op.create_index(op.f('ix_learning_resources_id'), 'resources', ['id'], unique=False, schema='learning')
    op.create_index('ix_resources__scope', 'resources', ['user_id'], unique=False, schema='learning')
    op.create_table('memory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', memu.database.postgres.models.TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', memu.database.postgres.models.TZDateTime(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('happened_at', sa.DateTime(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['learning.resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='learning'
    )
    op.create_index(op.f('ix_learning_memory_items_id'), 'memory_items', ['id'], unique=False, schema='learning')
    op.create_index('ix_memory_items__scope', 'memory_items', ['user_id'], unique=False, schema='learning')
    op.create_table('category_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', memu.database.postgres.models.TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', memu.database.postgres.models.TZDateTime(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['learning.memory_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['learning.memory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='learning'
    )
    op.create_index('idx_category_items_unique', 'category_items', ['item_id', 'category_id'], unique=True, schema='learning')
    op.create_index('ix_category_items__scope', 'category_items', ['user_id'], unique=False, schema='learning')
    op.create_index(op.f('ix_learning_category_items_id'), 'category_items', ['id'], unique=False, schema='learning')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_category_items_id'), table_name='category_items', schema='learning')
    op.drop_index('ix_category_items__scope', table_name='category_items', schema='learning')
    op.drop_index('idx_category_items_unique', table_name='category_items', schema='learning')
    op.drop_table('category_items', schema='learning')
    op.drop_index('ix_memory_items__scope', table_name='memory_items', schema='learning')
    op.drop_index(op.f('ix_learning_memory_items_id'), table_name='memory_items', schema='learning')
    op.drop_table('memory_items', schema='learning')
    op.drop_index('ix_resources__scope', table_name='resources', schema='learning')
    op.drop_index(op.f('ix_learning_resources_id'), table_name='resources', schema='learning')
    op.drop_table('resources', schema='learning')
    op.drop_index('ix_memory_categories__scope', table_name='memory_categories', schema='learning')
    op.drop_index(op.f('ix_learning_memory_categories_name'), table_name='memory_categories', schema='learning')
    op.drop_index(op.f('ix_learning_memory_categories_id'), table_name='memory_categories', schema='learning')
    op.drop_table('memory_categories', schema='learning')
    # ### end Alembic commands ###
