"""add_workspace_id_to_learning_tables

Revision ID: 299a8f5f0acd
Revises: 1e04a0ab1067
Create Date: 2026-03-02 05:26:13.837299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '299a8f5f0acd'
down_revision: Union[str, None] = '1e04a0ab1067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_items', sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='learning')
    op.drop_index(op.f('ix_category_items__scope'), table_name='category_items', schema='learning')
    op.create_index('ix_category_items__scope', 'category_items', ['user_id', 'workspace_id'], unique=False, schema='learning')
    op.add_column('memory_categories', sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='learning')
    op.drop_index(op.f('ix_memory_categories__scope'), table_name='memory_categories', schema='learning')
    op.create_index('ix_memory_categories__scope', 'memory_categories', ['user_id', 'workspace_id'], unique=False, schema='learning')
    op.add_column('memory_items', sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='learning')
    op.drop_index(op.f('ix_memory_items__scope'), table_name='memory_items', schema='learning')
    op.create_index('ix_memory_items__scope', 'memory_items', ['user_id', 'workspace_id'], unique=False, schema='learning')
    op.add_column('resources', sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='learning')
    op.drop_index(op.f('ix_resources__scope'), table_name='resources', schema='learning')
    op.create_index('ix_resources__scope', 'resources', ['user_id', 'workspace_id'], unique=False, schema='learning')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resources__scope', table_name='resources', schema='learning')
    op.create_index(op.f('ix_resources__scope'), 'resources', ['user_id'], unique=False, schema='learning')
    op.drop_column('resources', 'workspace_id', schema='learning')
    op.drop_index('ix_memory_items__scope', table_name='memory_items', schema='learning')
    op.create_index(op.f('ix_memory_items__scope'), 'memory_items', ['user_id'], unique=False, schema='learning')
    op.drop_column('memory_items', 'workspace_id', schema='learning')
    op.drop_index('ix_memory_categories__scope', table_name='memory_categories', schema='learning')
    op.create_index(op.f('ix_memory_categories__scope'), 'memory_categories', ['user_id'], unique=False, schema='learning')
    op.drop_column('memory_categories', 'workspace_id', schema='learning')
    op.drop_index('ix_category_items__scope', table_name='category_items', schema='learning')
    op.create_index(op.f('ix_category_items__scope'), 'category_items', ['user_id'], unique=False, schema='learning')
    op.drop_column('category_items', 'workspace_id', schema='learning')
    # ### end Alembic commands ###
